/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { VoteOption } from './VoteOption.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { VoteOptionService } from './VoteOption.service';
import { VoteOptionController } from './VoteOption.controller';

@Module({
  imports: [TypeOrmModule.forFeature([VoteOption])],
  providers: [VoteOptionService],
  exports: [VoteOptionService],
  controllers: [VoteOptionController],
})
export class VoteOptionModule {}
