/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { VoteOption, VoteOptionCreate } from './dtos/VoteOption.dto';
import { VoteOptionController } from './VoteOption.controller';
import { VoteOptionService } from './VoteOption.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('VoteOptionController', () => {
  let controller: VoteOptionController;
  let spyService: VoteOptionService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: VoteOptionService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [VoteOptionController],
      providers: [VoteOptionService, ApiServiceProvider],
    }).compile();

    controller = module.get<VoteOptionController>(VoteOptionController);
    spyService = module.get<VoteOptionService>(VoteOptionService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call VoteOptionController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call VoteOptionController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new VoteOption();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
