/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Voter, VoterCreate } from './dtos/Voter.dto';
import { VoterController } from './Voter.controller';
import { VoterService } from './Voter.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('VoterController', () => {
  let controller: VoterController;
  let spyService: VoterService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: VoterService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [VoterController],
      providers: [VoterService, ApiServiceProvider],
    }).compile();

    controller = module.get<VoterController>(VoterController);
    spyService = module.get<VoterService>(VoterService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call VoterController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call VoterController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Voter();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
