/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Voter } from './Voter.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { VoterService } from './Voter.service';
import { VoterController } from './Voter.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Voter])],
  providers: [VoterService],
  exports: [VoterService],
  controllers: [VoterController],
})
export class VoterModule {}
