/**
 * This file generated by Apso.
 */
import { VoteQuestionModule } from './VoteQuestion/VoteQuestion.module';
import { VoteOptionModule } from './VoteOption/VoteOption.module';
import { VoterModule } from './Voter/Voter.module';
import { VoteModule } from './Vote/Vote.module';

export default [VoteQuestionModule, VoteOptionModule, VoterModule, VoteModule];
