/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { VoteQuestion, VoteQuestionCreate } from './dtos/VoteQuestion.dto';
import { VoteQuestionController } from './VoteQuestion.controller';
import { VoteQuestionService } from './VoteQuestion.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('VoteQuestionController', () => {
  let controller: VoteQuestionController;
  let spyService: VoteQuestionService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: VoteQuestionService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [VoteQuestionController],
      providers: [VoteQuestionService, ApiServiceProvider],
    }).compile();

    controller = module.get<VoteQuestionController>(VoteQuestionController);
    spyService = module.get<VoteQuestionService>(VoteQuestionService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call VoteQuestionController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call VoteQuestionController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new VoteQuestion();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
