/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { VoteQuestion } from './VoteQuestion.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { VoteQuestionService } from './VoteQuestion.service';
import { VoteQuestionController } from './VoteQuestion.controller';

@Module({
  imports: [TypeOrmModule.forFeature([VoteQuestion])],
  providers: [VoteQuestionService],
  exports: [VoteQuestionService],
  controllers: [VoteQuestionController],
})
export class VoteQuestionModule {}
