/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import { VoteQuestion, VoteQuestionCreate } from './dtos/VoteQuestion.dto';
import { VoteQuestionService } from './VoteQuestion.service';

@Crud({
  model: {
    type: VoteQuestion,
  },
  dto: {
    create: VoteQuestionCreate,
    update: VoteQuestion,
    replace: VoteQuestion,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('VoteQuestions')
@ApiTags('VoteQuestions')
export class VoteQuestionController implements CrudController<VoteQuestion> {
  constructor(public service: VoteQuestionService) {}

  get base(): CrudController<VoteQuestion> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple VoteQuestions' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single VoteQuestion' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single VoteQuestion' })
  @ApiBody({
    type: VoteQuestionCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: VoteQuestion) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleVoteQuestions' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<VoteQuestion>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single VoteQuestion' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: VoteQuestion) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single VoteQuestion' })
  replace(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: VoteQuestion) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single VoteQuestion' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
