import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class VoteCreate {
  @ApiProperty()
  vote_option_id: string;
  @ApiProperty()
  voter_id: string;
}

export class Vote {
  @ApiProperty()
  id: number;
  @ApiProperty()
  vote_option_id: string;
  @ApiProperty()
  voter_id: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
