/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Vote, VoteCreate } from './dtos/Vote.dto';
import { VoteController } from './Vote.controller';
import { VoteService } from './Vote.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('VoteController', () => {
  let controller: VoteController;
  let spyService: VoteService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: VoteService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [VoteController],
      providers: [VoteService, ApiServiceProvider],
    }).compile();

    controller = module.get<VoteController>(VoteController);
    spyService = module.get<VoteService>(VoteService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call VoteController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call VoteController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Vote();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
