/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Vote } from './Vote.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { VoteService } from './Vote.service';
import { VoteController } from './Vote.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Vote])],
  providers: [VoteService],
  exports: [VoteService],
  controllers: [VoteController],
})
export class VoteModule {}
