import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class VoterCreate {
  @ApiProperty()
  wallet_address: string;
}

export class Voter {
  @ApiProperty()
  id: number;
  @ApiProperty()
  wallet_address: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
