import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class VoteOptionCreate {
  @ApiProperty()
  option_text: string;
  @ApiProperty()
  vote_question_id: string;
}

export class VoteOption {
  @ApiProperty()
  id: number;
  @ApiProperty()
  option_text: string;
  @ApiProperty()
  vote_question_id: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
