import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class VoteQuestionCreate {
  @ApiProperty()
  question_text: string;
}

export class VoteQuestion {
  @ApiProperty()
  id: number;
  @ApiProperty()
  question_text: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
